[package]
name = "oss_backend"
version = "0.1.0"
authors = ["Maxheart <samuelhenrykurniawan@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# web framework
rocket = "0.4.4"

# ORM
diesel = { version = "1.4.3", features = ["postgres"] }
dotenv = "0.9.0"

# password hashing
pwhash = "0.3"
